# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: setup node
      uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
      with:
        version: 6.10.0
    - uses: actions/setup-node@v2
      with:
        node-version: "16.x"
        cache: pnpm
    - name: pnpm install and build
      run: | 
        pnpm install
        pnpm build
        npm test
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: |
          build
